name: semver

on:
    pull_request:
        branches: master
        paths:
            - "src/**"
            - "package.json"
            - "package-lock.json"

jobs:
    validate:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  ref: master
                  fetch-depth: 0
            - uses: actions/setup-node@v2
            - id: current_semver
              run: echo "::set-output name=value::$(node -e 'console.log(require("./package.json").version)')"
            - uses: actions/checkout@v2
            - id: branch_semver
              run: echo "::set-output name=value::$(node -e 'console.log(require("./package.json").version)')"
            - if: ${{ steps.current_version.outputs.value }} == ${{ steps.branch_semver.outputs.value }}
              run: |
                  echo "${{ steps.current_version.outputs.value }} == ${{ steps.branch_semver.outputs.value }}"
                  exit 1
            - run: |
                  echo "${{ steps.current_version.outputs.value }} != ${{ steps.branch_semver.outputs.value }}"
